"""
Django settings for apartmentapi project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = '%s/apartment/static/' % BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aa$3sc8quxnhel+xv)^gyjje5ez123w3&431*erx19o=d&akid'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []  # '192.168.1.74'

import pymysql

pymysql.install_as_MySQLdb()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apartment',
    # 'ckeditor',
    # 'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

# CKEDITOR_UPLOAD_PATH = "ckeditors/images/"
Client_id = 'B4AiBktDgat7mopb9la0DTltAjLZUx9ad49rwqYu'
Client_secret = 'UU9ptwUBvT3wWa4jSB5Tl4k0r3hBuB7epFOObdGzAROK8S6Mf5EeHQmPzsDpmATauFjSX0NzLzjovAgIAOMQkov6UP5HJvjg1eKDvNw8hnm4LXl8EdsdEdQzGdC3G362'

AUTH_USER_MODEL = 'apartment.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# settings.py

ZALOPAY_CONFIG = {
    'app_id': '553',
    'key1': '9phuAOYhan4urywHTh0ndEXiV3pKHr5Q',
    'key2': 'Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3',
    'create_order_endpoint': 'https://sandbox.zalopay.com.vn/v001/tpe/createorder',
}

ROOT_URLCONF = 'apartmentapi.urls'
# settings.py

ZALOPAY_KEY2 = 'Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apartmentapi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apartmentdb',
        'USER': 'root',
        'PASSWORD': 'prolaanh00',
        'HOST': ''  # mặc định localhost
    }
}

# ALLOWED_HOSTS = ['192.168.1.109']


import cloudinary

cloudinary.config(
    cloud_name="dbecreoes",
    api_key="543635266845376",
    api_secret="32WNqMLBNCYm-wisY_0zr44BNRA"
)
#the email settings


MAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "huroth200012@gmail.com"
EMAIL_HOST_PASSWORD = "tglhdtlzawbmjswl"
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CLIENT_ID = 'jpFk2rrdFNhgimtgApzoZsGlfSfrHhjQ3V21AgwD'
CLIENT_SECRET = 'JReD8XON7aMZhfuz10qWPwY1jzD6Rn6vsTpKmWGwawTHC8IONqWcVIbZXmLOcKNHfM5Da8T6Qjb8b6naaP6l99FUd903b7jge0mT1bT7GcmrQ6e5xc7zyGI2DZLcEsAu'
