# Generated by Django 5.0.3 on 2024-05-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='content',
            new_name='content_choice',
        ),
        migrations.AlterField(
            model_name='response',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='apartment.resident'),
        ),
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='apartment.survey'),
        ),
        migrations.AlterField(
            model_name='service',
            name='residents',
            field=models.ManyToManyField(related_name='service', through='apartment.ResidentFee', to='apartment.resident'),
        ),
    ]
