# Generated by Django 5.0.3 on 2024-05-10 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_item_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='electroniclockeritem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='monthlyfee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='monthlyfee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reflectionform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reflectionform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='repairservices',
            name='description',
        ),
        migrations.RemoveField(
            model_name='repairservices',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservationvehicle',
            name='monthlyfee_ptr',
        ),
        migrations.RemoveField(
            model_name='reservationvehicle',
            name='reservation_name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='description',
        ),
        migrations.AddField(
            model_name='repairservices',
            name='repair_name',
            field=models.CharField(default='phis', max_length=50),
        ),
        migrations.AddField(
            model_name='reservationvehicle',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationvehicle',
            name='reservation_vehicle_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reservationvehicle',
            name='residents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.resident'),
        ),
        migrations.AddField(
            model_name='reservationvehicle',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_infor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Manager', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user_infor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Resident', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
