# Generated by Django 5.0.3 on 2024-05-10 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_remove_choice_description_remove_choice_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationvehicle',
            name='residents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_reservation', to='apartment.resident'),
        ),
    ]
