# Generated by Django 5.0.3 on 2024-06-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_residentfee_created_date_alter_choice_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentfee',
            name='payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentfee',
            name='status',
            field=models.CharField(choices=[('Đang chờ xử lý', 'Đang chờ xử lý'), ('Không thể xử lý', 'Không thể xử lý'), ('Đã đăng ký', 'Đã đăng ký')], default='Đang chờ xử lý', max_length=50),
        ),
    ]
