# Generated by Django 5.0.3 on 2024-06-07 15:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_residentfee_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.IntegerField(max_length=40, null=True)),
                ('content', models.CharField(max_length=50, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='residentfee',
            name='status',
            field=models.CharField(choices=[('Đang chờ xử lý', 'Đang xử lý'), ('Không thể xử lý', 'Thất Bại'), ('Đã đăng ký', 'Thành Công')], default='Đang chờ xử lý', max_length=50),
        ),
    ]
